language: node_js
node_js:
   - "8"
before_install:
   - git config
   - git config credential.helper "store --file=.git/credentials"; echo "https://${GITHUB_OAUTH_TOKEN}:@github.com" > .git/credentials 2>/dev/null
   - git config --global user.email "864615516@qq.com"
   - git config --global user.name "sli"
install:
 - npm install
cache:
 directories:
  - "node_modules"
deploy:
 provider: pages
 skip_cleanup: true
 github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
 on:
  branch: master
